### ISSUE TITLE
Has anyone tried Roberta Base?

### ISSUE THREAD

**Issue by kaliaanup** [georgian-io/Multimodal-Toolkit#17]
It gives me classification error. Like one of the class completely blanks out. It does not happen in case of Bert Base.

```
     precision    recall  f1-score   support

         Yes     0.0000    0.0000    0.0000        63
          No     0.5000    1.0000    0.6667        63
```

**Comment by akashsaravanan-georgian** [comment]
Closing this issue as there's not enough information and it's been a year. My guess is that the model either overfit heavily or there's something wonky with the data that caused the model to only predict No.
