### ISSUE TITLE
Support for other BERT models

### ISSUE THREAD

**Issue by dsi-idc** [georgian-io/Multimodal-Toolkit#26]
hi!
Can I expect the package to work on other BERT models (not listed in the ReadMe) -- e.g., [longformer ](https://huggingface.co/allenai/longformer-base-4096)

thank you!

**Comment by akashsaravanan-georgian** [comment]
There's no direct support for models not listed in the readme. However, you should be able to add such models on your own. Take a look at `multimodal_transformers/model/tabular_transformers.py` for existing implementations and feel free to open up a PR if you do add models :)
