### ISSUE TITLE
Please check the colab notebook

### ISSUE THREAD

**Issue by Aymen-lab** [georgian-io/Multimodal-Toolkit#43]
Hello,

The notebook was running fine 2 months ago, but no longer after the huggingface update.
I think there is a problem with the load_data_from_folder function, because I get the following error message when training:
AxisError: axis 1 is out of bounds for array of dimension 1 (see pic.).
<img width="681" alt="image" src="https://user-images.githubusercontent.com/75539650/236495399-a3d53064-7053-4ff2-a7da-79a983a27910.png">

Thanks for helping!

**Comment by jtfields** [comment]
I am adding longformer support to the Multimodal Toolkit (see pull request section for details).  The colab notebook is now completing 1 epoch and I am receiving the same error that Aymen-lab describes above.  I've had issues in the past with the calc_classification_metrics(p: EvalPrediction) section and it seems like this is the step where the error is occurring.

**Comment by Aymen-lab** [comment]
Hi @jtfields , 

Thank you for your reply. I hope this problem get solved soon. 
I will keep tracking your pull request :)

**Comment by jtfields** [comment]
@Aymen-lab I think this might be related to Issue #41.  Look at the code I posted for this error.

**Comment by akashsaravanan-georgian** [comment]
Hi @Aymen-lab,

John is on the number with this one. I've made a PR #44 to fix this, but feel free to just copy the relevant block of code from the PR or John's solution above to handle this for now.
