### ISSUE TITLE
Misleading TabularConfig parameter in Example code

### ISSUE THREAD

**Issue by speter00** [georgian-io/Multimodal-Toolkit#53]
According to the Example usage in the documentation: https://multimodal-toolkit.readthedocs.io/en/latest/notes/introduction.html
the **TabularConfig** class has an init parameter called **use_num_bn** (in the example, it is set to **False**) for deciding whether to use 
**Batch Normalization**. In the actual **TabularConfig** class however there is no such parameter, instead there is a **numerical_bn** parameter with a **default value of True**. There is also a kwargs parameter.

Right now, if someone follows the example code, they will mistakenly -and probably unknowingly- end up using Batch Normalization, because the **use_num_bn** parameter will not actually do anything (it will just be absorbed as a kwarg), and instead the **default True** value of **numerical_bn** will take effect. 

The TabularConfig class's documentation is correct, only the Example section has this mistake. I advise updating the Example code with the numerical_bn parameter instead to avoid misunderstandings.

**Comment by akashsaravanan-georgian** [comment]
Hi @speter00 good catch, thanks for letting us know! We'll make sure to fix this in our next release. Feel free to send a PR if you're interested!
