### ISSUE TITLE
Batch Normalization is done even with False BN parameter

### ISSUE THREAD

**Issue by speter00** [georgian-io/Multimodal-Toolkit#54]
In the model/tabular_combiner.py script, everytime MLP is initialized the bn parameter is set to True, ignoring the value of self.numerical_bn (the parameter normally responsible for determining whether batch normalization is done or not). This causes most feature combination methods to end up using Batch Normalization even if the numerical_bn parameter was set to False in TabularConfig.
An easy fix is to simply do bn=self.numerical_bn each time MLP is called, so that the parameter is accounted for instead of using True everytime.

**Comment by akashsaravanan-georgian** [comment]
Thank you @speter00, this looks like a duplicate of #53. We'll fix in the next release but feel free to send a PR and we can merge it in!

**Comment by speter00** [comment]
It is not a duplicate. This is a separate issue. #53 was about a misleading parameter name used in an example. This is about a part of the code ignoring the value of this same parameter, and instead using a fixed value.

**Comment by akashsaravanan-georgian** [comment]
Ah whoops, apologies I misread it then. But feel free to send a PR :)
