### ISSUE TITLE
[Question] Are numerical and categorical features used for fine-tuning the BERT(or LLMs)?

### ISSUE THREAD

**Issue by anirbandey303** [georgian-io/Multimodal-Toolkit#74]
Hi Developers,

I have a naive question, could you please help me understand: 

- During the model training, are the weights and biases of the BERT model(or any other supported model) changing? (IF yes,) is it taking the numerical and categorical features into account or is it being used as a feature (along with the vector-embeddings from the LLM) by the MLP that does the classification?

**Comment by akashsaravanan-georgian** [comment]
Hi @anirbandey303,

Yes, the pre-trained language model (such as BERT) weights do change. 

The numerical/categorical features are not used by the language (BERT) model. They are sent as features to the MLP alongside the output of the language model. The architecture diagram [here](https://multimodal-toolkit.readthedocs.io/en/latest/index.html) might help!

**Comment by akashsaravanan-georgian** [comment]
Happy to help :)
