### ISSUE TITLE
Is there a way to save the preprocessing objects for inference? (OneHotEncoder, Scaler)

### ISSUE THREAD

**Issue by kkristacia** [georgian-io/Multimodal-Toolkit#76]
Hi thank you for developing this package! I want to be able to load the already saved model, then use it for inference like in production. How can I let the inference dataset to go through the same preprocessing steps eg. OneHotEncoding of categorical variables, scaling?

**Comment by akashsaravanan-georgian** [comment]
Hi @kkristacia, 
To load the model, you just need to run the same steps as creating the model. The only difference is that while calling `model = AutoModelWithTabular.from_pretrained(...)` make sure you set the first argument `pretrained_model_name_or_path` to the path that you saved your model in. 

Similarly, to preprocess the inference dataset, I would recommend running `data.load_data()` function with the same parameters used in the `load_data_from_folder` while training. 

Please let me know if you run into any other issues and I can help you solve it! :)

**Comment by kkristacia** [comment]
Hi Akash, thanks for the clarification. Yea I was hoping for some way to not use the training data during inference. Definitely will be great if future versions can have the functionality!

**Comment by akashsaravanan-georgian** [comment]
Thanks @dsunart! I'm reopening this issue as a feature request. It should be added in as part of our next release!

**Comment by akashsaravanan-georgian** [comment]
Hey @kkristacia and @dsunart, happy to note that this is now part of the toolkit. You can see this in action in [this example](https://github.com/georgian-io/Multimodal-Toolkit/blob/master/examples/inference.py).
